---
- name: api_docker
  hosts: all
  become: true
  gather_facts: true
  roles:
    - db
    - api
    - nginx

  # name: db_docker
  # hosts: all
  # become: true
  # gather_facts: true
  # roles:
  #   - db